### ISSUE TITLE
Error saving and loading targeting_structs

### ISSUE THREAD

**Issue by T-Applesmith** [T-Applesmith/TDL_RL_Framework#48]

**Comment by T-Applesmith** [comment]
Traceback (most recent call last):
  File "C:\My Docs Sam\Sam's Projects\TDL_Test\TDL_RL_Framework\engine.py", line 635, in <module>
    main()
  File "C:\My Docs Sam\Sam's Projects\TDL_Test\TDL_RL_Framework\engine.py", line 629, in main
    play_game(player, entities, game_map, previous_game_maps, message_log, game_state, root_console, con, panel, constants, config_dict)
  File "C:\My Docs Sam\Sam's Projects\TDL_Test\TDL_RL_Framework\engine.py", line 172, in play_game
    if targeting_structure.struct_name == 'Circle':
AttributeError: 'NoneType' object has no attribute 'struct_name'

**Comment by T-Applesmith** [comment]
found that the fireball scroll didn't have a targeting_structure, issue resolved
